import type {
  CheckRun,
  ListCheckRunsResponse,
} from "@/types/github";

const NOW = () => new Date().toISOString();

function mockChecks(): CheckRun[] {
  return [
    {
      id: "ci-build",
      name: "ci / build",
      source: "github-actions · workflow #482",
      state: "success",
      required: true,
      url: "https://github.com/example/repo/actions/runs/12345",
      startedAt: NOW(),
      durationMs: 72_000,
    },
    {
      id: "ci-unit-tests",
      name: "ci / unit-tests",
      source: "github-actions · workflow #482",
      state: "success",
      required: true,
      url: "https://github.com/example/repo/actions/runs/12346",
      startedAt: NOW(),
      durationMs: 124_000,
    },
    {
      id: "ci-lint",
      name: "ci / lint",
      source: "github-actions · workflow #482",
      state: "success",
      required: false,
      url: "https://github.com/example/repo/actions/runs/12347",
      startedAt: NOW(),
      durationMs: 12_000,
    },
    {
      id: "ci-typecheck",
      name: "ci / typecheck",
      source: "github-actions · workflow #482",
      state: "success",
      required: true,
      url: "https://github.com/example/repo/actions/runs/12348",
      startedAt: NOW(),
      durationMs: 38_000,
    },
    {
      id: "codeql-security",
      name: "codeql / security",
      source: "codeql-analysis · run #41",
      state: "success",
      required: false,
      url: "https://github.com/example/repo/security/code-scanning",
      startedAt: NOW(),
      durationMs: 262_000,
    },
    {
      id: "ci-integration-postgres",
      name: "ci / integration (postgres)",
      source: "github-actions · workflow #482 · 2 retries",
      state: "failure",
      required: true,
      url: "https://github.com/example/repo/actions/runs/12349",
      startedAt: NOW(),
      durationMs: 221_000,
    },
    {
      id: "ci-e2e-firefox",
      name: "ci / e2e (firefox)",
      source: "github-actions · workflow #482",
      state: "timed_out",
      required: false,
      url: "https://github.com/example/repo/actions/runs/12350",
      startedAt: NOW(),
      durationMs: 1_800_000,
    },
    {
      id: "ci-e2e-chromium",
      name: "ci / e2e (chromium)",
      source: "github-actions · workflow #482 · started 2m ago",
      state: "in_progress",
      required: false,
      url: "https://github.com/example/repo/actions/runs/12351",
      startedAt: NOW(),
      durationMs: null,
    },
    {
      id: "ci-e2e-webkit",
      name: "ci / e2e (webkit)",
      source: "github-actions · workflow #482 · started 2m ago",
      state: "in_progress",
      required: false,
      url: "https://github.com/example/repo/actions/runs/12352",
      startedAt: NOW(),
      durationMs: null,
    },
    {
      id: "vercel-preview",
      name: "vercel / preview",
      source: "vercel · approval needed",
      state: "action_required",
      required: false,
      url: "https://vercel.com/example/preview",
      startedAt: null,
      durationMs: null,
    },
    {
      id: "deploy-preview",
      name: "deploy / preview",
      source: "vercel · waiting on integration test",
      state: "queued",
      required: false,
      url: null,
      startedAt: null,
      durationMs: null,
    },
    {
      id: "danger-pr-size",
      name: "danger / pr-size",
      source: "danger · advisory",
      state: "neutral",
      required: false,
      url: "https://github.com/example/repo/actions/runs/12353",
      startedAt: NOW(),
      durationMs: 8_000,
    },
    {
      id: "ci-mobile-build",
      name: "ci / mobile-build",
      source: "github-actions · skipped (no mobile changes)",
      state: "skipped",
      required: false,
      url: null,
      startedAt: null,
      durationMs: null,
    },
    {
      id: "ci-e2e-safari",
      name: "ci / e2e (safari)",
      source: "github-actions · superseded by re-run",
      state: "cancelled",
      required: false,
      url: "https://github.com/example/repo/actions/runs/12354",
      startedAt: NOW(),
      durationMs: 12_000,
    },
    {
      id: "ci-smoke-stale",
      name: "ci / smoke",
      source: "workflow #480 · result from older head",
      state: "stale",
      required: false,
      url: "https://github.com/example/repo/actions/runs/12300",
      startedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      durationMs: 45_000,
    },
  ];
}

export async function mockListCheckRuns(_repoPath: string, _number: number): Promise<ListCheckRunsResponse> {
  await new Promise((resolve) => setTimeout(resolve, 80));
  return {
    headSha: "c4f1a82d3e9b1a7d4f8c2e6b9a3d5f7c1e0b9a8d",
    fetchedAt: NOW(),
    checks: mockChecks(),
  };
}
